"""update tag-genre relationship

Revision ID: 0ab013a40d99
Revises: 2c581cc67d8d
Create Date: 2025-06-19 23:32:05.539464

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ab013a40d99"
down_revision: Union[str, None] = "2c581cc67d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag_genres",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("genres", sa.Column("note", sa.Text(), nullable=True))
    with op.batch_alter_table("tags") as batch_op:
        batch_op.drop_constraint(op.f("fk_genre"), type_="foreignkey")
    op.drop_column("tags", "genre_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("genre_id", sa.VARCHAR(), nullable=True))
    op.create_foreign_key(
        op.f("fk_genre"), "tags", "genres", ["genre_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("genres", "note")
    op.drop_table("tag_genres")
    # ### end Alembic commands ###
