"""genre update

Revision ID: 2c581cc67d8d
Revises: 90c6e34a679f
Create Date: 2025-06-18 02:16:36.445548

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c581cc67d8d"
down_revision: Union[str, None] = "90c6e34a679f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # genres テーブルを削除して再作成（空なので安全）
    op.drop_table("genres")
    op.create_table(
        "genres",
        sa.Column("id", sa.String, primary_key=True),
        sa.Column("name", sa.String, nullable=True),
    )

    # tags.genre カラムを削除（元が ForeignKey でなければ問題なし）
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_column("genre")  # ← 元カラム名が 'genre' で正しければ OK

    # tags テーブルに genre_id カラム追加 → 外部キー制約付きで追加
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("genre_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_genre", "genres", ["genre_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("genre", sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.drop_column("tags", "genre_id")
    op.add_column("genres", sa.Column("registered_at", sa.DATETIME(), nullable=True))
    op.add_column("genres", sa.Column("name_ja", sa.VARCHAR(), nullable=True))
    op.add_column("genres", sa.Column("name_en", sa.VARCHAR(), nullable=False))
    op.drop_column("genres", "name")
    op.drop_column("genres", "id")
    # ### end Alembic commands ###
