"""update genre

Revision ID: 4f164f7b59cc
Revises: 0ab013a40d99
Create Date: 2025-06-20 00:17:25.189708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f164f7b59cc"
down_revision: Union[str, None] = "0ab013a40d99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("genres") as batch_op:
        batch_op.alter_column("name", existing_type=sa.String(), nullable=False)
    # op.alter_column('genres', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("genres", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
