"""add index

Revision ID: 4f930f619424
Revises: 4f164f7b59cc
Create Date: 2025-06-21 11:19:53.314943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f930f619424'
down_revision: Union[str, None] = '4f164f7b59cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_categories_name', 'categories', ['name'], unique=False)
    op.create_index('idx_genres_name', 'genres', ['name'], unique=False)
    op.create_index('idx_image_tags_confidence', 'image_tags', ['confidence'], unique=False)
    op.create_index('idx_image_tags_image_confidence', 'image_tags', ['image_id', 'confidence'], unique=False)
    op.create_index('idx_image_tags_image_id', 'image_tags', ['image_id'], unique=False)
    op.create_index('idx_image_tags_image_tag', 'image_tags', ['image_id', 'tag_id'], unique=False)
    op.create_index('idx_image_tags_model_name', 'image_tags', ['model_name'], unique=False)
    op.create_index('idx_image_tags_tag_confidence', 'image_tags', ['tag_id', 'confidence'], unique=False)
    op.create_index('idx_image_tags_tag_id', 'image_tags', ['tag_id'], unique=False)
    op.create_index('idx_image_tags_tag_image', 'image_tags', ['tag_id', 'image_id'], unique=False)
    op.create_index('idx_images_created_at', 'images', ['created_at'], unique=False)
    op.create_index('idx_images_favorite_sensitive', 'images', ['is_favorite', 'is_sensitive'], unique=False)
    op.create_index('idx_images_id_desc', 'images', ['id'], unique=False)
    op.create_index('idx_images_is_favorite', 'images', ['is_favorite'], unique=False)
    op.create_index('idx_images_is_sensitive', 'images', ['is_sensitive'], unique=False)
    op.create_index('idx_images_registered_at', 'images', ['registered_at'], unique=False)
    op.create_index('idx_images_tag_embedding', 'images', ['tag_embedding'], unique=False)
    op.create_index('idx_images_view_count', 'images', ['view_count'], unique=False)
    op.create_index('idx_poses_image_flipped', 'poses', ['image_id', 'is_flipped'], unique=False)
    op.create_index('idx_poses_image_id', 'poses', ['image_id'], unique=False)
    op.create_index('idx_poses_is_flipped', 'poses', ['is_flipped'], unique=False)
    op.create_index('idx_tag_genres_genre_id', 'tag_genres', ['genre_id'], unique=False)
    op.create_index('idx_tag_genres_tag_genre', 'tag_genres', ['tag_id', 'genre_id'], unique=False)
    op.create_index('idx_tag_genres_tag_id', 'tag_genres', ['tag_id'], unique=False)
    op.create_index('idx_tag_translations_language', 'tag_translations', ['language'], unique=False)
    op.create_index('idx_tag_translations_tag_id', 'tag_translations', ['tag_id'], unique=False)
    op.create_index('idx_tag_translations_tag_language', 'tag_translations', ['tag_id', 'language'], unique=False)
    op.create_index('idx_tag_translations_translated_name', 'tag_translations', ['translated_name'], unique=False)
    op.create_index('idx_tags_category_id', 'tags', ['category_id'], unique=False)
    op.create_index('idx_tags_disable', 'tags', ['disable'], unique=False)
    op.create_index('idx_tags_embedding', 'tags', ['embedding'], unique=False)
    op.create_index('idx_tags_is_sensitive', 'tags', ['is_sensitive'], unique=False)
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.create_index('idx_tags_registered_at', 'tags', ['registered_at'], unique=False)
    op.create_index('idx_tags_sensitive_disable', 'tags', ['is_sensitive', 'disable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tags_sensitive_disable', table_name='tags')
    op.drop_index('idx_tags_registered_at', table_name='tags')
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_index('idx_tags_is_sensitive', table_name='tags')
    op.drop_index('idx_tags_embedding', table_name='tags')
    op.drop_index('idx_tags_disable', table_name='tags')
    op.drop_index('idx_tags_category_id', table_name='tags')
    op.drop_index('idx_tag_translations_translated_name', table_name='tag_translations')
    op.drop_index('idx_tag_translations_tag_language', table_name='tag_translations')
    op.drop_index('idx_tag_translations_tag_id', table_name='tag_translations')
    op.drop_index('idx_tag_translations_language', table_name='tag_translations')
    op.drop_index('idx_tag_genres_tag_id', table_name='tag_genres')
    op.drop_index('idx_tag_genres_tag_genre', table_name='tag_genres')
    op.drop_index('idx_tag_genres_genre_id', table_name='tag_genres')
    op.drop_index('idx_poses_is_flipped', table_name='poses')
    op.drop_index('idx_poses_image_id', table_name='poses')
    op.drop_index('idx_poses_image_flipped', table_name='poses')
    op.drop_index('idx_images_view_count', table_name='images')
    op.drop_index('idx_images_tag_embedding', table_name='images')
    op.drop_index('idx_images_registered_at', table_name='images')
    op.drop_index('idx_images_is_sensitive', table_name='images')
    op.drop_index('idx_images_is_favorite', table_name='images')
    op.drop_index('idx_images_id_desc', table_name='images')
    op.drop_index('idx_images_favorite_sensitive', table_name='images')
    op.drop_index('idx_images_created_at', table_name='images')
    op.drop_index('idx_image_tags_tag_image', table_name='image_tags')
    op.drop_index('idx_image_tags_tag_id', table_name='image_tags')
    op.drop_index('idx_image_tags_tag_confidence', table_name='image_tags')
    op.drop_index('idx_image_tags_model_name', table_name='image_tags')
    op.drop_index('idx_image_tags_image_tag', table_name='image_tags')
    op.drop_index('idx_image_tags_image_id', table_name='image_tags')
    op.drop_index('idx_image_tags_image_confidence', table_name='image_tags')
    op.drop_index('idx_image_tags_confidence', table_name='image_tags')
    op.drop_index('idx_genres_name', table_name='genres')
    op.drop_index('idx_categories_name', table_name='categories')
    # ### end Alembic commands ###
