"""add folder_table

Revision ID: 56f1b0f62bfe
Revises: a4b629adeb48
Create Date: 2025-07-12 19:34:46.930258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f1b0f62bfe'
down_revision: Union[str, None] = 'a4b629adeb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_image_folders_name', 'image_folders', ['name'], unique=False)
    op.create_table('image_folder_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['image_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'image_id', name='uix_folder_image')
    )
    op.create_index('idx_folder_image_order', 'image_folder_associations', ['folder_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_folder_image_order', table_name='image_folder_associations')
    op.drop_table('image_folder_associations')
    op.drop_index('idx_image_folders_name', table_name='image_folders')
    op.drop_table('image_folders')
    # ### end Alembic commands ###
