"""add tag favorite columns with default

Revision ID: a4b629adeb48
Revises: 4f930f619424
Create Date: 2025-07-12 12:09:39.301384

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4b629adeb48"
down_revision: Union[str, None] = "4f930f619424"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_images_tag_embedding'), table_name='images')
    # op.add_column(
    #     "tags",
    #     sa.Column(
    #         "is_favorite", sa.Boolean(), server_default=sa.text("0"), nullable=False
    #     ),
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "is_favorite")
    op.create_index(
        op.f("idx_images_tag_embedding"), "images", ["tag_embedding"], unique=False
    )
    # ### end Alembic commands ###
