"""upfdate tables

Revision ID: 3ee6bc927f86
Revises: 56f1b0f62bfe
Create Date: 2025-07-27 18:00:09.815727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee6bc927f86'
down_revision: Union[str, None] = '56f1b0f62bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_image_folders_name'), table_name='image_folders')
    op.create_index(op.f('ix_image_folders_name'), 'image_folders', ['name'], unique=True)
    op.drop_index(op.f('idx_image_tags_confidence'), table_name='image_tags')
    op.drop_index(op.f('idx_image_tags_image_confidence'), table_name='image_tags')
    op.drop_index(op.f('idx_image_tags_model_name'), table_name='image_tags')
    op.alter_column('images', 'registered_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('images', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('images', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('idx_images_created_at'), table_name='images')
    op.drop_index(op.f('idx_images_registered_at'), table_name='images')
    op.drop_index(op.f('idx_images_view_count'), table_name='images')
    op.create_index(op.f('ix_images_is_favorite'), 'images', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_images_is_sensitive'), 'images', ['is_sensitive'], unique=False)
    op.alter_column('poses', 'is_flipped',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('idx_poses_is_flipped'), table_name='poses')
    op.drop_index(op.f('idx_tag_translations_translated_name'), table_name='tag_translations')
    op.create_index(op.f('ix_tag_translations_translated_name'), 'tag_translations', ['translated_name'], unique=False)
    op.alter_column('tags', 'registered_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tags', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tags', 'disable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('idx_tags_disable'), table_name='tags')
    op.drop_index(op.f('idx_tags_embedding'), table_name='tags')
    op.drop_index(op.f('idx_tags_name'), table_name='tags')
    op.drop_index(op.f('idx_tags_registered_at'), table_name='tags')
    op.create_index(op.f('ix_tags_disable'), 'tags', ['disable'], unique=False)
    op.create_index(op.f('ix_tags_is_sensitive'), 'tags', ['is_sensitive'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_is_sensitive'), table_name='tags')
    op.drop_index(op.f('ix_tags_disable'), table_name='tags')
    op.create_index(op.f('idx_tags_registered_at'), 'tags', ['registered_at'], unique=False)
    op.create_index(op.f('idx_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('idx_tags_embedding'), 'tags', ['embedding'], unique=False)
    op.create_index(op.f('idx_tags_disable'), 'tags', ['disable'], unique=False)
    op.alter_column('tags', 'disable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tags', 'registered_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_tag_translations_translated_name'), table_name='tag_translations')
    op.create_index(op.f('idx_tag_translations_translated_name'), 'tag_translations', ['translated_name'], unique=False)
    op.create_index(op.f('idx_poses_is_flipped'), 'poses', ['is_flipped'], unique=False)
    op.alter_column('poses', 'is_flipped',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_images_is_sensitive'), table_name='images')
    op.drop_index(op.f('ix_images_is_favorite'), table_name='images')
    op.create_index(op.f('idx_images_view_count'), 'images', ['view_count'], unique=False)
    op.create_index(op.f('idx_images_registered_at'), 'images', ['registered_at'], unique=False)
    op.create_index(op.f('idx_images_created_at'), 'images', ['created_at'], unique=False)
    op.alter_column('images', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('images', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('images', 'registered_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('idx_image_tags_model_name'), 'image_tags', ['model_name'], unique=False)
    op.create_index(op.f('idx_image_tags_image_confidence'), 'image_tags', ['image_id', 'confidence'], unique=False)
    op.create_index(op.f('idx_image_tags_confidence'), 'image_tags', ['confidence'], unique=False)
    op.drop_index(op.f('ix_image_folders_name'), table_name='image_folders')
    op.create_index(op.f('idx_image_folders_name'), 'image_folders', ['name'], unique=False)
    # ### end Alembic commands ###
