[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=11.2.1",
]

[dependency-groups]
dev = [
    "watchdog>=6.0.0",
]
