SENSITIVE_KEYWORDS = {
    "bdsm",
    "gag",
    "bound",
    "bondage",
    "ball gag",
    "nipples",
    "gagged",
    "shibari",
    "crotch rope",
    "completely nude",
    "restrained",
    "bound arms",
    "bound wrists",
    "public nudity",
    "public indecency",
    "slave",
    "object insertion",
    "anal object insertion",
    "anal",
    "pussy",
    "pussy juice",
    "penis",
    "sex",
    "vaginal",
    "pubic hair",
    "female pubic hair",
    "sex machine",
    "censored nipples",
    "handcuffs",
    "anus",
    "sex toy",
    "stationary restraints",
    "vaginal object insertion",
    "bound legs",
    "uterus",
    "chained",
    "internal cumshot",
    "ejaculation",
    "blindfold",
    "nipple piercing",
    "bit gag",
    "clothed male nude female",
    "male pubic hair",
    "pov crotch",
    "irrumatio",
    "spread pussy",
    "puckered anus",
    "urethra",
    "clitoris",
    "licking penis",
    "after fellatio",
    "urethral insertion",
    "wiffle gag",
    "ring gag",
    "nipple pull",
    "torture",
    "invisible penis",
    "large areolae",
    "imminent anal",
}
